name: 01 Docker Multi Build and use buildkit-cache-dance


on:
  #  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  build-and-test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
        id: setup-buildxxx


      - name: dependencies build cache
        uses: actions/cache@v4
        id: cache
        with:
          path: gradle-build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          cache-map: |
            {
              "gradle-build-cache" : "/home/gradle/.gradle"
            }
      

      - name: Build Dcoker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: false
          tags: todoproject:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max